
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: ntt1902/spring-petclinic-admin-server
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
      restartPolicy: Always
