apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - name: "http"
      port: 9090        
      targetPort: 9090  
  type: ClusterIP       