apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
  labels:
    app: genai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: ntt1902/spring-petclinic-genai-service
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: OPENAI_API_KEY
            - name: AZURE_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_KEY
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_ENDPOINT
      restartPolicy: Always