apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
  labels:
    app: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - name: "http"
      port: 8084       
      targetPort: 8084  
  type: ClusterIP       
