apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: springcommunity/spring-petclinic-genai-service
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: OPENAI_API_KEY
            - name: AZURE_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_KEY
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: AZURE_OPENAI_ENDPOINT
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.petclinic.svc.cluster.local:9411/api/v2/spans"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
          ports:
            - containerPort: 8084
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
spec:
  selector:
    app: genai-service
  ports:
    - port: 8084
      targetPort: 8084