apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: petclinic
  labels:
    app: tracing-server
spec:
  selector:
    app: tracing-server
  ports:
    - name: "http"
      port: 9411        
      targetPort: 9411  
  type: ClusterIP      
